**Interprétation des coefficients d'une régression linéaire.** (en lien avec Frisch-Waugh).

In [35]:
from sklearn.datasets import fetch_openml
import pandas as pd
survey = fetch_openml(data_id=534, as_frame=True, parser='auto')

In [6]:
df = survey.data[survey.feature_names]
df.describe(include="all")

,EDUCATION,SOUTH,SEX,EXPERIENCE,UNION,AGE,RACE,OCCUPATION,SECTOR,MARR
count,534.000000,534,534,534.000000,534,534.000000,534,534,534,534
unique,NaN,2,2,NaN,2,NaN,3,6,3,2
top,NaN,no,male,NaN,not_member,NaN,White,Other,Other,Married
freq,NaN,378,289,NaN,438,NaN,440,156,411,350
mean,13.018727,NaN,NaN,17.822097,NaN,36.833333,NaN,NaN,NaN,NaN
std,2.615373,NaN,NaN,12.379710,NaN,11.726573,NaN,NaN,NaN,NaN
min,2.000000,NaN,NaN,0.000000,NaN,18.000000,NaN,NaN,NaN,NaN
25%,12.000000,NaN,NaN,8.000000,NaN,28.000000,NaN,NaN,NaN,NaN
50%,12.000000,NaN,NaN,15.000000,NaN,35.000000,NaN,NaN,NaN,NaN
75%,15.000000,NaN,NaN,26.000000,NaN,44.000000,NaN,NaN,NaN,NaN
max,18.000000,NaN,NaN,55.000000,NaN,64.000000,NaN,NaN,NaN,NaN

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 534 entries, 0 to 533
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EDUCATION   534 non-null    int64
 1   SOUTH       534 non-null    category
 2   SEX         534 non-null    category
 3   EXPERIENCE  534 non-null    int64
 4   UNION       534 non-null    category
 5   AGE         534 non-null    int64
 6   RACE        534 non-null    category
 7   OCCUPATION  534 non-null    category
 8   SECTOR      534 non-null    category
 9   MARR        534 non-null    category
dtypes: category(7), int64(3)
memory usage: 17.2 KB

In [8]:
categorical_features=df.select_dtypes(include='category')
categorical_features

,SOUTH,SEX,UNION,RACE,OCCUPATION,SECTOR,MARR
0,no,female,not_member,Hispanic,Other,Manufacturing,Married
1,no,female,not_member,White,Other,Manufacturing,Married
2,no,male,not_member,White,Other,Manufacturing,Unmarried
3,no,male,not_member,White,Other,Other,Unmarried
4,no,male,not_member,White,Other,Other,Married
...,...,...,...,...,...,...,...
529,no,male,not_member,White,Professional,Other,Unmarried
530,no,female,not_member,Other,Professional,Other,Married
531,no,female,member,Other,Professional,Other,Married
532,yes,male,member,White,Professional,Other,Married
533,no,male,not_member,White,Professional,Manufacturing,Married

In [11]:
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder(drop='first',sparse_output=False)
array_cat_binary=encoder.fit_transform(categorical_features)
array_cat_binary

array([[0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 1., 1., ..., 1., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [1., 1., 0., ..., 0., 1., 0.],
       [0., 1., 1., ..., 1., 0., 0.]])

In [12]:
encoded_col_names = encoder.get_feature_names_out(categorical_features.columns)
encoded_col_names

array(['SOUTH_yes', 'SEX_male', 'UNION_not_member', 'RACE_Other',
       'RACE_White', 'OCCUPATION_Management', 'OCCUPATION_Other',
       'OCCUPATION_Professional', 'OCCUPATION_Sales',
       'OCCUPATION_Service', 'SECTOR_Manufacturing', 'SECTOR_Other',
       'MARR_Unmarried'], dtype=object)

In [15]:
# Création d'un DataFrame à partir de l'array encodé, en utilisant l'index du DataFrame original
df_cat_binary = pd.DataFrame(array_cat_binary, columns=encoded_col_names, index=df.index)

In [20]:
# dataframe final (avec variables numériques + variables catégorielles encodées)
df_final=pd.concat([df.select_dtypes(include='number'),df_cat_binary], axis=1)
df_final.describe()

,EDUCATION,EXPERIENCE,AGE,SOUTH_yes,SEX_male,UNION_not_member,RACE_Other,RACE_White,OCCUPATION_Management,OCCUPATION_Other,OCCUPATION_Professional,OCCUPATION_Sales,OCCUPATION_Service,SECTOR_Manufacturing,SECTOR_Other,MARR_Unmarried
count,534.000000,534.000000,534.000000,534.000000,534.000000,534.000000,534.000000,534.000000,534.000000,534.000000,534.000000,534.000000,534.000000,534.000000,534.000000,534.000000
mean,13.018727,17.822097,36.833333,0.292135,0.541199,0.820225,0.125468,0.823970,0.102996,0.292135,0.196629,0.071161,0.155431,0.185393,0.769663,0.344569
std,2.615373,12.379710,11.726573,0.455170,0.498767,0.384360,0.331560,0.381203,0.304239,0.455170,0.397822,0.257335,0.362655,0.388981,0.421443,0.475673
min,2.000000,0.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,12.000000,8.000000,28.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
50%,12.000000,15.000000,35.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
75%,15.000000,26.000000,44.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
max,18.000000,55.000000,64.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [21]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 534 entries, 0 to 533
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   EDUCATION                534 non-null    int64
 1   EXPERIENCE               534 non-null    int64
 2   AGE                      534 non-null    int64
 3   SOUTH_yes                534 non-null    float64
 4   SEX_male                 534 non-null    float64
 5   UNION_not_member         534 non-null    float64
 6   RACE_Other               534 non-null    float64
 7   RACE_White               534 non-null    float64
 8   OCCUPATION_Management    534 non-null    float64
 9   OCCUPATION_Other         534 non-null    float64
 10  OCCUPATION_Professional  534 non-null    float64
 11  OCCUPATION_Sales         534 non-null    float64
 12  OCCUPATION_Service       534 non-null    float64
 13  SECTOR_Manufacturing     534 non-null    float64
 14  SECTOR_Other             534 non-null    float64
 15  MARR_Unmarried           534 non-null    float64
dtypes: float64(13), int64(3)
memory usage: 66.9 KB

In [17]:
Y = survey.target
Y.describe()

count    534.000000
mean       9.024064
std        5.139097
min        1.000000
25%        5.250000
50%        7.780000
75%       11.250000
max       44.500000
Name: WAGE, dtype: float64

In [26]:
from sklearn.linear_model import LinearRegression
mod_lin1=LinearRegression().fit(df_final,Y)
mod_lin1.coef_

array([ 0.81279135,  0.24484501, -0.15802823, -0.56274247,  1.94252212,
       -1.60168787, -0.23136243,  0.60650843,  3.26819795, -0.02232313,
        1.93462877, -0.79564391, -0.70717721,  0.56348715, -0.47740163,
       -0.30050151])

In [ ]:
#En particulier
print(f'coefficient de AGE {mod_lin_coef_[2]} et de EXPERIENCE

In [23]:
df=df_final.drop('EXPERIENCE',axis=1)

In [24]:
df.columns

Index(['EDUCATION', 'AGE', 'SOUTH_yes', 'SEX_male', 'UNION_not_member',
       'RACE_Other', 'RACE_White', 'OCCUPATION_Management', 'OCCUPATION_Other',
       'OCCUPATION_Professional', 'OCCUPATION_Sales', 'OCCUPATION_Service',
       'SECTOR_Manufacturing', 'SECTOR_Other', 'MARR_Unmarried'],
      dtype='object')

In [27]:
from sklearn.linear_model import LinearRegression
mod_lin2=LinearRegression().fit(df,Y)
mod_lin2.coef_

array([ 0.56774419,  0.08658999, -0.56481125,  1.9374903 , -1.60077725,
       -0.22913621,  0.60920757,  3.27119453, -0.01902657,  1.94637637,
       -0.79302965, -0.70626864,  0.56068663, -0.47845151, -0.29611039])

In [31]:
#En particulier : 
print(f'coefficient de AGE {mod_lin1.coef_[2]} et de EXPERIENCE {mod_lin.coef_[1]} dans le modèle complet')
print(f'coefficient de AGE {mod_lin2.coef_[1]}  dans le modèle sans EXPERIENCE')

coefficient de AGE -0.15802822851237278 et de EXPERIENCE 0.08658998768847145 dans le modèle complet
coefficient de AGE 0.08658998768847145  dans le modèle sans EXPERIENCE

Remarque : coef negatif pour AGE quand EXPERIENCE est déjà présente  mais positif sans la feature EXPERIENCE.

In [34]:
df_final.corr()# énorme corrélation entre AGE et EXPERIENCE

,EDUCATION,EXPERIENCE,AGE,SOUTH_yes,SEX_male,UNION_not_member,RACE_Other,RACE_White,OCCUPATION_Management,OCCUPATION_Other,OCCUPATION_Professional,OCCUPATION_Sales,OCCUPATION_Service,SECTOR_Manufacturing,SECTOR_Other,MARR_Unmarried
EDUCATION,1.000000,-0.352676,-0.150019,-0.140143,-0.002031,0.023886,-0.054641,0.123751,0.202708,-0.382852,0.495948,0.020318,-0.232533,-0.119605,0.175839,0.035522
EXPERIENCE,-0.352676,1.000000,0.977961,-0.007407,-0.075230,-0.117926,0.029674,-0.016985,0.006867,0.012570,-0.094599,0.013993,0.082228,0.063746,-0.100646,-0.270900
AGE,-0.150019,0.977961,1.000000,-0.038665,-0.079179,-0.119466,0.019382,0.009373,0.052676,-0.071706,0.009451,0.019481,0.035220,0.040926,-0.067385,-0.278947
SOUTH_yes,-0.140143,-0.007407,-0.038665,1.000000,0.021264,0.086275,0.092331,-0.124774,-0.055106,0.049145,-0.089875,0.030416,0.008556,-0.062747,0.028682,-0.006523
SEX_male,-0.002031,-0.075230,-0.079179,0.021264,1.000000,-0.157027,0.031083,-0.020992,0.052350,0.343568,-0.036175,0.006351,-0.113262,0.062097,-0.137745,0.011225
UNION_not_member,0.023886,-0.117926,-0.119466,0.086275,-0.157027,1.000000,-0.087672,0.078125,0.110507,-0.171103,-0.050597,0.110615,-0.027978,-0.040185,0.079775,0.093164
RACE_Other,-0.054641,0.029674,0.019382,0.092331,0.031083,-0.087672,1.000000,-0.819486,-0.016753,-0.007124,-0.087821,-0.038873,0.102766,0.022965,-0.021045,0.034663
RACE_White,0.123751,-0.016985,0.009373,-0.124774,-0.020992,0.078125,-0.819486,1.000000,0.011027,0.015794,0.080207,0.051432,-0.113857,-0.007251,-0.007611,-0.047704
OCCUPATION_Management,0.202708,0.006867,0.052676,-0.055106,0.052350,0.110507,-0.016753,0.011027,1.000000,-0.217686,-0.167641,-0.093792,-0.145367,-0.066532,0.097577,-0.025297
OCCUPATION_Other,-0.382852,0.012570,-0.071706,0.049145,0.343568,-0.171103,-0.007124,0.015794,-0.217686,1.000000,-0.317821,-0.177815,-0.275592,0.414105,-0.509244,0.002142
OCCUPATION_Professional,0.495948,-0.094599,0.009451,-0.089875,-0.036175,-0.050597,-0.087821,0.080207,-0.167641,-0.317821,1.000000,-0.136936,-0.212235,-0.090523,0.113978,-0.051355
OCCUPATION_Sales,0.020318,0.013993,0.019481,0.030416,0.006351,0.110615,-0.038873,0.051432,-0.093792,-0.177815,-0.136936,1.000000,-0.118741,-0.057072,0.082222,-0.062744
OCCUPATION_Service,-0.232533,0.082228,0.035220,0.008556,-0.113262,-0.027978,0.102766,-0.113857,-0.145367,-0.275592,-0.212235,-0.118741,1.000000,-0.178056,0.210132,0.069615
SECTOR_Manufacturing,-0.119605,0.063746,0.040926,-0.062747,0.062097,-0.040185,0.022965,-0.007251,-0.066532,0.414105,-0.090523,-0.057072,-0.178056,1.000000,-0.872050,-0.031559
SECTOR_Other,0.175839,-0.100646,-0.067385,0.028682,-0.137745,0.079775,-0.021045,-0.007611,0.097577,-0.509244,0.113978,0.082222,0.210132,-0.872050,1.000000,0.050370
MARR_Unmarried,0.035522,-0.270900,-0.278947,-0.006523,0.011225,0.093164,0.034663,-0.047704,-0.025297,0.002142,-0.051355,-0.062744,0.069615,-0.031559,0.050370,1.000000